# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-18 16:00
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ncaacards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userentry',
            name='apid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
